#!/bin/bash
echo "making backup of config"
for i in $(seq 1 3); do for c in $(seq 1 2); do echo p"$i"$c;cp /etc/sysconfig/network-scripts/ifcfg-p"$i"p$c /etc/sysconfig/network-scripts/ifcfg-p"$i"p$c.bk; done; done
echo "doing sed....."
for i in $(seq 1 3); do for c in $(seq 1 2); do echo p"$i"$c;sed -i "" 's/ONBOOT=yes/ONBOOT=no/g' /etc/sysconfig/network-scripts/ifcfg-p"$i"p$c; done; done
echo "restarting network..."
systemctl restart network
